# SPDX-FileCopyrightText: 2026 Benoit Rolandeau <benoit.rolandeau@allcircuits.com>
#
# SPDX-License-Identifier: Apache-2.0

# Contains the parameters read by the act_logger_manager package.
logs:
  # This defines the log level for the whole logger manager.
  level: debug

  # Contains the parameters for the console external logger.
  console:
    # This defines the minimum log level printed by the console logger.
    level: debug
