# SPDX-FileCopyrightText: 2024 Théo Magne <theo.magne@allcircuits.com>
#
# SPDX-License-Identifier: LicenseRef-ALLCircuits-ACT-1.1

name: act_aws_iot_core
description: "Package to interact with aws iot core using amplify credentials"
publish_to: none

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  windows:

environment:
  sdk: ^3.11.1
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter

  amplify_flutter: ^2.6.4

  amplify_auth_cognito: ^2.6.4

  aws_common: ^0.7.8

  aws_signature_v4: ^0.6.6

  equatable: ^2.0.7

  mqtt_client: ^10.9.2

  mutex: ^3.1.0

  uuid: ^4.5.1

  act_amplify_cognito:
    path: ../act_amplify_cognito

  # This contains the amplify core library
  act_amplify_core:
    path: ../act_amplify_core

  act_config_manager:
    path: ../act_config_manager

  act_dart_timer:
    path: ../act_dart_timer

  act_dart_utility:
    path: ../act_dart_utility

  # Default global manager
  act_global_manager:
    path: ../act_global_manager

  # Internet access. For ObserverInternet
  act_internet_connectivity_manager:
    path: ../act_internet_connectivity_manager

  # Contains the structure to create services and managers
  act_life_cycle:
    path: ../act_life_cycle

  # Contains the logger manager
  act_logger_manager:
    path: ../act_logger_manager

  # Shared auth classes. For the ObserverAuth
  act_shared_auth:
    path: ../act_shared_auth

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
