# SPDX-FileCopyrightText: 2020 - 2023 Sami Kouatli <sami.kouatli@allcircuits.com>
# SPDX-FileCopyrightText: 2023 Anthony Loiseau <anthony.loiseau@allcircuits.com>
# SPDX-FileCopyrightText: 2023 Benoit Rolandeau <benoit.rolandeau@allcircuits.com>
#
# SPDX-License-Identifier: LicenseRef-ALLCircuits-ACT-1.1

# Project definition
name: act_intl_ui
description: This package contains graphical helpers linked to translations.

# Project configuration
publish_to: none

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.11.1
  flutter: ">=3.29.0"

# Project dependencies
dependencies:
  # Flutter framework
  flutter:
    sdk: flutter

  # Widget rendering static HTML and CSS as Flutter widgets
  flutter_html: ^3.0.0

  # Help to implement value based equality without explicit override
  equatable: ^2.0.7

  # Implement the BLoC (Business Logic Component) design pattern
  flutter_bloc: ^9.1.1

  # Code to deal with internationalized/localized messages
  intl: ^0.20.2

  act_flutter_utility:
    path: ../act_flutter_utility

  # Global manager
  act_global_manager:
    path: ../act_global_manager

  # Non-graphical internationalization helpers
  act_intl:
    path: ../act_intl

# Dependencies used by developer
dev_dependencies:
  # API to test Flutter applications
  flutter_test:
    sdk: flutter

  # Recommended lints for Flutter apps
  flutter_lints: ^6.0.0
