# SPDX-FileCopyrightText: 2025 Benoit Rolandeau <benoit.rolandeau@allcircuits.com>
#
# SPDX-License-Identifier: LicenseRef-ALLCircuits-ACT-1.1

name: act_oauth2_core
description: This package contains the common elements to connect to OAuth 2.0
  client from Identity Providers.
publish_to: none

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.11.1
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.7

  flutter_appauth: ^9.0.1

  mutex: ^3.1.0

  act_dart_utility:
    path: ../act_dart_utility

  # Default global manager
  act_global_manager:
    path: ../act_global_manager

  # Easily create managers
  act_life_cycle:
    path: ../act_life_cycle

  act_local_storage_manager:
    path: ../act_local_storage_manager

  # Logger manager
  act_logger_manager:
    path: ../act_logger_manager

  # Shared auth library
  act_shared_auth:
    path: ../act_shared_auth

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
