# SPDX-FileCopyrightText: 2024 Benoit Rolandeau <benoit.rolandeau@allcircuits.com>
#
# SPDX-License-Identifier: LicenseRef-ALLCircuits-ACT-1.1

name: act_shared_auth_ui
description: This package completes the act_shared_auth and offers widgets, blocs, page, etc.
publish_to: none

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.11.1
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.7

  # This is the router manager
  act_router_manager:
    path: ../act_router_manager

  # This is the shared authentication package
  act_shared_auth:
    path: ../act_shared_auth

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
