# SPDX-FileCopyrightText: 2025 Anthony Loiseau <anthony.loiseau@allcircuits.com>
#
# SPDX-License-Identifier: LicenseRef-ALLCircuits-ACT-1.1

name: act_remote_local_vers_file_manager
description: "Act remote localized and versioned file manager."
publish_to: none

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  windows:

environment:
  sdk: ^3.11.1
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.7

  # Path manipulation tools
  path: ^1.9.1

  act_config_manager:
    path: ../act_config_manager

  # Utilities around dart core types
  act_dart_utility:
    path: ../act_dart_utility

  # Global manager
  act_global_manager:
    path: ../act_global_manager

  # Utilities around dart core types
  act_intl:
    path: ../act_intl

  # Easily create managers
  act_life_cycle:
    path: ../act_life_cycle

  # Loggers
  act_logger_manager:
    path: ../act_logger_manager

  # Help fetching remotely stored files
  act_remote_storage_manager:
    path: ../act_remote_storage_manager

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
