# SPDX-FileCopyrightText: 2020 - 2023 Sami Kouatli <sami.kouatli@allcircuits.com>
# SPDX-FileCopyrightText: 2023 Anthony Loiseau <anthony.loiseau@allcircuits.com>
# SPDX-FileCopyrightText: 2023 Benoit Rolandeau <benoit.rolandeau@allcircuits.com>
#
# SPDX-License-Identifier: LicenseRef-ALLCircuits-ACT-1.1

# Project definition
name: act_platform_manager
description: Useful class to manage platform

# Project configuration
publish_to: none

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.11.1
  flutter: ">=3.29.0"

# Project dependencies
dependencies:
  # Flutter framework
  flutter:
    sdk: flutter

  # Get current device information from within the Flutter application.
  device_info_plus: ^11.5.0

  # Easily create managers
  act_life_cycle:
    path: ../act_life_cycle

# Dependencies used by developer
dev_dependencies:
  # API to test Flutter applications
  flutter_test:
    sdk: flutter

  # Recommended lints for Flutter apps
  flutter_lints: ^6.0.0
