# SPDX-FileCopyrightText: 2026 Benoit Rolandeau <benoit.rolandeau@allcircuits.com>
#
# SPDX-License-Identifier: LicenseRef-ALLCircuits-ACT-1.1

sdk:
  - "3.44.6"

stages:
  - analyze:
      - group:
          - analyze: --fatal-infos .
