# SPDX-FileCopyrightText: 2020 - 2023 Sami Kouatli <sami.kouatli@allcircuits.com>
# SPDX-FileCopyrightText: 2023 Anthony Loiseau <anthony.loiseau@allcircuits.com>
# SPDX-FileCopyrightText: 2023 Benoit Rolandeau <benoit.rolandeau@allcircuits.com>
#
# SPDX-License-Identifier: LicenseRef-ALLCircuits-ACT-1.1

# Project definition
name: act_global_manager
description: This package contains the default global_manager which has to be
  extended in the app.

# Project configuration
publish_to: none

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.11.1
  flutter: ">=3.29.0"

# Project dependencies
dependencies:
  # Flutter framework
  flutter:
    sdk: flutter

  # Decouple the interface from concrete implementation and
  # access the concrete implementation from everywhere in your App
  get_it: ^8.0.3

  # Query information about the application package
  package_info_plus: ^8.3.0

  # Flutter AC Technologies dependencies
  act_config_manager:
    path: ../act_config_manager

  act_foundation:
    path: ../act_foundation

  # Contains utilities for Dart
  act_dart_utility:
    path: ../act_dart_utility

  # Easily create managers
  act_life_cycle:
    path: ../act_life_cycle

  # Logger manager
  act_logger_manager:
    path: ../act_logger_manager

# Dependencies used by developer
dev_dependencies:
  # API to test Flutter applications
  flutter_test:
    sdk: flutter

  # Recommended lints for Flutter apps
  flutter_lints: ^6.0.0
