# SPDX-FileCopyrightText: 2023 Nicolas Butet <nicolas.butet@allcircuits.com>
#
# SPDX-License-Identifier: LicenseRef-ALLCircuits-ACT-1.1

# Project definition
name: act_router_manager
description: This package contains a router manager.

# Project configuration
publish_to: none

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.11.1
  flutter: ">=3.29.0"

# Project dependencies
dependencies:
  # Flutter framework
  flutter:
    sdk: flutter

  # Help to implement value based equality without explicit override
  equatable: ^2.0.7

  # Implements the Router API
  go_router: ^15.1.3

  # Base errors/exceptions hierarchy
  act_foundation:
    path: ../act_foundation

  # Default global manager
  act_global_manager:
    path: ../act_global_manager

  # Easily create managers
  act_life_cycle:
    path: ../act_life_cycle

  # Logger manager
  act_logger_manager:
    path: ../act_logger_manager

# Dependencies used by developer
dev_dependencies:
  # API to test Flutter applications
  flutter_test:
    sdk: flutter

  # Recommended lints for Flutter apps
  flutter_lints: ^6.0.0
