# SPDX-FileCopyrightText: 2024 Benoit Rolandeau <benoit.rolandeau@allcircuits.com>
#
# SPDX-License-Identifier: LicenseRef-ALLCircuits-ACT-1.1

name: act_remote_storage_ui
description: "Contains helpful widgets to work with act_remote_storage_manager"
publish_to: none

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  windows:

environment:
  sdk: ^3.11.1
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter

  # Default global manager
  act_global_manager:
    path: ../act_global_manager

  # Storage manager
  act_remote_storage_manager:
    path: ../act_remote_storage_manager

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
