version = 1

[[annotations]]
path = ["Assets.xcassets/**", "Base.lproj/**"]
precedence = "override"
SPDX-FileCopyrightText = "2024 Benoit Rolandeau <borlnov.obsessio@gmail.com>"
SPDX-License-Identifier = "MIT"
