# SPDX-FileCopyrightText: 2023 Benoit Rolandeau <benoit.rolandeau@allcircuits.com>
#
# SPDX-License-Identifier: LicenseRef-ALLCircuits-ACT-1.1

name: act_thingsboard_client
description: Helpful package to use the Thingsboard client with app
publish_to: none

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.11.1
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter

  thingsboard_client:
    git:
      url: https://github.com/benoit-rolandeau-act/dart_thingsboard_client.git
      ref: fix-tb-storage-interface

  # Help to implement value based equality without explicit override
  equatable: ^2.0.7

  mutex: ^3.1.0

  act_config_manager:
    path: ../act_config_manager

  act_dart_utility:
    path: ../act_dart_utility

  # Base errors/exceptions hierarchy
  act_foundation:
    path: ../act_foundation

  # Default global manager
  act_global_manager:
    path: ../act_global_manager

  act_http_client_manager:
    path: ../act_http_client_manager

  # Flutter AC Technologies dependencies
  act_life_cycle:
    path: ../act_life_cycle

  act_local_storage_manager:
    path: ../act_local_storage_manager

  # Logger manager
  act_logger_manager:
    path: ../act_logger_manager

  # Shared auth library
  act_shared_auth:
    path: ../act_shared_auth

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
