# SPDX-FileCopyrightText: 2024 Théo Magne <theo.magne@allcircuits.com>
#
# SPDX-License-Identifier: LicenseRef-ALLCircuits-ACT-1.1

name: act_remote_storage_manager
description: This package contains the remote storage manager, which can be used
  to get files from a remote server.
publish_to: none

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  windows:

environment:
  sdk: ^3.11.1
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.7

  # Used to cache files
  flutter_cache_manager: ^3.4.1

  # Helps manipulating paths
  path: ^1.9.1

  # Used to get the application directory (cache, documents, etc.)
  path_provider: ^2.1.5

  # Provide the configuration for the storage manager
  act_config_manager:
    path: ../act_config_manager

  # Utilities around dart core types
  act_dart_utility:
    path: ../act_dart_utility

  # Base errors/exceptions hierarchy
  act_foundation:
    path: ../act_foundation

  # Global manager
  act_global_manager:
    path: ../act_global_manager

  # Easily create managers
  act_life_cycle:
    path: ../act_life_cycle

  # Loggers
  act_logger_manager:
    path: ../act_logger_manager

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
