# SPDX-FileCopyrightText: 2024 Benoit Rolandeau <benoit.rolandeau@allcircuits.com>
#
# SPDX-License-Identifier: LicenseRef-ALLCircuits-ACT-1.1

name: act_firebase_core
description: "This is the main package to manage firebase with our ACT libs"
publish_to: none

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.11.1
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.7

  firebase_core: ^3.14.0

  act_config_manager:
    path: ../act_config_manager

  act_foundation:
    path: ../act_foundation

  # Default global manager
  act_global_manager:
    path: ../act_global_manager

  # Contains default classes for managers
  act_life_cycle:
    path: ../act_life_cycle

  # Logger manager
  act_logger_manager:
    path: ../act_logger_manager

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
