# SPDX-FileCopyrightText: 2023 Anthony Loiseau <anthony.loiseau@allcircuits.com>
# SPDX-FileCopyrightText: 2023 Benoit Rolandeau <benoit.rolandeau@allcircuits.com>
#
# SPDX-License-Identifier: LicenseRef-ALLCircuits-ACT-1.1

name: act_enable_service_utility
description: The package contains utility classes to manage the enabling of services
publish_to: none

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  windows:

environment:
  sdk: ^3.11.1
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter

  # Open phone settings in app
  app_settings: ^6.1.1

  equatable: ^2.0.7

  act_life_cycle:
    path: ../act_life_cycle

  act_contextual_views_manager:
    path: ../act_contextual_views_manager

  act_dart_utility:
    path: ../act_dart_utility

  act_global_manager:
    path: ../act_global_manager

  act_app_life_cycle_manager:
    path: ../act_app_life_cycle_manager

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints for Flutter apps
  flutter_lints: ^6.0.0
