# SPDX-FileCopyrightText: 2024 Benoit Rolandeau <benoit.rolandeau@allcircuits.com>
#
# SPDX-License-Identifier: LicenseRef-ALLCircuits-ACT-1.1

name: act_splash_screen_manager
description: Useful package to support native splash screens in mobile applications
publish_to: none

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  web:

environment:
  sdk: ^3.11.1
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_native_splash: ^2.4.6

  # Easily create managers
  act_life_cycle:
    path: ../act_life_cycle

  # Logger manager
  act_logger_manager:
    path: ../act_logger_manager

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
