# SPDX-FileCopyrightText: 2020 - 2023 Sami Kouatli <sami.kouatli@allcircuits.com>
# SPDX-FileCopyrightText: 2023 Anthony Loiseau <anthony.loiseau@allcircuits.com>
# SPDX-FileCopyrightText: 2023 Benoit Rolandeau <benoit.rolandeau@allcircuits.com>
#
# SPDX-License-Identifier: LicenseRef-ALLCircuits-ACT-1.1

name: act_local_storage_manager
description: This package contains two managers to store properties and secrets
publish_to: none

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.11.1
  flutter: ">=3.29.0"

dependencies:
  # Flutter framework
  flutter:
    sdk: flutter

  equatable: ^2.0.7

  # Store/Load data in secure storage
  flutter_secure_storage: ^9.2.4

  # Wrap platform-specific persistent storage for simple data
  # TODO(brolandeau): when updating the lib, verify if we still need to override `shared_preferences_android`
  shared_preferences: ^2.5.3

  act_config_manager:
    path: ../act_config_manager

  # Extend Dart functionalities
  act_dart_utility:
    path: ../act_dart_utility

  act_foundation:
    path: ../act_foundation

  # Default global manager
  act_global_manager:
    path: ../act_global_manager

  # Flutter AC Technologies dependencies
  act_life_cycle:
    path: ../act_life_cycle

  # Logger manager
  act_logger_manager:
    path: ../act_logger_manager

dev_dependencies:
  # API to test Flutter applications
  flutter_test:
    sdk: flutter

  # Recommended lints for Flutter apps
  flutter_lints: ^6.0.0

dependency_overrides:
  # This is needed to fix problem with building for Android app
  # The shared preferences doesn't use the latest android package which is needed by flutter.
  shared_preferences_android: 2.4.10
