# SPDX-FileCopyrightText: 2026 Benoit Rolandeau <benoit.rolandeau@allcircuits.com>
#
# SPDX-License-Identifier: LicenseRef-ALLCircuits-ACT-1.1

name: act_dart_value_keeper
description: This package provides a way to keep a value and update it based on
  a stream or an initialization function.
publish_to: none

environment:
  sdk: ^3.11.1
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter

  act_foundation:
    path: ../act_foundation

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
