# SPDX-FileCopyrightText: 2023 Benoit Rolandeau <benoit.rolandeau@allcircuits.com>
#
# SPDX-License-Identifier: LicenseRef-ALLCircuits-ACT-1.1

name: act_tic_manager
description: This package contains a tic manager which helps to display HMI in pace
publish_to: none

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.11.1
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter

  rxdart: ^0.28.0

  act_life_cycle:
    path: ../act_life_cycle

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
