// SPDX-FileCopyrightText: 2026 Benoit Rolandeau <borlnov.obsessio@gmail.com>
//
// SPDX-License-Identifier: Apache-2.0

import 'dart:convert';
import 'dart:typed_data';

import 'package:equatable/equatable.dart';
import 'package:open_cine_prod_tools/models/sync/ocpt_field_stamp.dart';

/// The app's own domain shape of one unit of synchronised work: every [OcptFieldStamp] a device is
/// pushing in one go, generated by `OcptChangesetService`.
///
/// This is the JSON that becomes an `OcptChangesetEnvelope.payload` — `packages/ocpt_sync_protocol`
/// never decodes it, and never learns a table or column name doing so
/// (`docs/adr/0009-offline-first-sync-through-a-domain-blind-relay.md`). [encode] and
/// [OcptChangeset.decode] are the two ends of that opaque byte string; every other member is this
/// class's own JSON shape, carried the same way every other model in `lib/models/` carries one.
class OcptChangeset extends Equatable {
  static const _fieldStampsKey = 'fieldStamps';

  /// Every field stamp this changeset carries.
  final List<OcptFieldStamp> fieldStamps;

  /// Creates a changeset out of [fieldStamps].
  const OcptChangeset({required this.fieldStamps});

  /// Parses a changeset from the JSON object [toJson] writes.
  factory OcptChangeset.fromJson(Map<String, dynamic> json) => OcptChangeset(
    fieldStamps: [
      for (final entry in json[_fieldStampsKey] as List<dynamic>)
        OcptFieldStamp.fromJson(entry as Map<String, dynamic>),
    ],
  );

  /// Parses a changeset from the bytes an `OcptChangesetEnvelope.payload` carries — the inverse of
  /// [encode].
  factory OcptChangeset.decode(Uint8List bytes) =>
      OcptChangeset.fromJson(jsonDecode(utf8.decode(bytes)) as Map<String, dynamic>);

  /// Serialises this changeset to the JSON object it is carried as.
  Map<String, dynamic> toJson() => {
    _fieldStampsKey: [for (final stamp in fieldStamps) stamp.toJson()],
  };

  /// Serialises this changeset to the JSON bytes an `OcptChangesetEnvelope.payload` carries — the
  /// inverse of [OcptChangeset.decode].
  Uint8List encode() => Uint8List.fromList(utf8.encode(jsonEncode(toJson())));

  @override
  List<Object?> get props => [fieldStamps];

  @override
  String toString() => 'OcptChangeset(fieldStamps: $fieldStamps)';
}
