// SPDX-FileCopyrightText: 2020 - 2023 Sami Kouatli <sami.kouatli@allcircuits.com>
// SPDX-FileCopyrightText: 2023 Anthony Loiseau <anthony.loiseau@allcircuits.com>
// SPDX-FileCopyrightText: 2023 Benoit Rolandeau <benoit.rolandeau@allcircuits.com>
//
// SPDX-License-Identifier: LicenseRef-ALLCircuits-ACT-1.1

import 'package:act_foundation/act_foundation.dart';

/// This class provides a set of [bool] helpers, not provided by Dart.
///
/// String parsing methods
/// ----------------------
///
/// Others basic types feature both
/// - a toString function which encodes a value as a String
/// - a parse/tryParse pair which decodes the string into a value
///
/// Unfortunately Dart [bool] only features a toString at the time of writing.
/// This helper provides those two missing functions.
///
/// Extending [bool] type
/// ---------------------
///
/// Extending bool type (to inject parse functions in it for example)
/// is unfortunately prohibited by Dart.
sealed class BoolUtility {
  /// This is the integer value used to represent false
  static const falseIntValue = 0;

  /// This is the integer value used to represent true
  static const trueIntValue = 1;

  /// Parse boolean value from an integer value.
  ///
  /// If the [value] is equal to [falseIntValue], false is returned, otherwise true is returned.
  static bool parseFromInt(int value) => value != falseIntValue;

  /// Convert a boolean value to an integer value.
  ///
  /// If the [value] is true, [trueIntValue] is returned, otherwise [falseIntValue] is returned.
  // In that case the parameter is not really positional since it is the only one and we know what
  // it is, so we can ignore the warning about positional boolean parameters.
  // ignore: avoid_positional_boolean_parameters
  static int toInt(bool value) => value ? trueIntValue : falseIntValue;

  /// Parse [source] as a [bool].
  ///
  /// The [source] is expected to be either "true", "1", "false" or "0", whichever case
  /// (upper, lower or mixed case). It must not be null.
  ///
  /// This method is compatible with [bool.toString] since it recognize strings
  /// generated by [bool.toString] (and a few more).
  ///
  /// If the [source] string does not contain a valid boolean literal,
  /// a [FormatException] is thrown.
  ///
  /// See also [tryParse].
  static bool parse(String source) {
    final sourceLower = source.toLowerCase();

    if (sourceLower == "true" || sourceLower == "1") {
      return true;
    }
    if (sourceLower == "false" || sourceLower == "0") {
      return false;
    }

    throw FormatException("Literal does not describe a boolean", source);
  }

  /// Parse [source] as a [bool].
  ///
  /// The [source] is expected to be either "true" or "false", whichever case
  /// (upper, lower or mixed case). It must not be null.
  ///
  /// This method is compatible with [bool.toString] since it recognize strings
  /// generated by [bool.toString] (and a few more).
  ///
  /// If the [source] string does not contain a valid boolean literal,
  /// null is returned.
  ///
  /// See also [parse].
  static bool? tryParse(String source, {MixinActLogger? logger}) {
    bool? boolValue;
    try {
      boolValue = parse(source);
    } on FormatException {
      logger?.w("The string given: '$source' does not contain a valid boolean literal");
    }

    return boolValue;
  }
}
