version = 1

[[annotations]]
path = ["Runner.xcodeproj/**", "Runner.xcworkspace/**"]
precedence = "override"
SPDX-FileCopyrightText = "2024 Benoit Rolandeau <borlnov.obsessio@gmail.com>"
SPDX-License-Identifier = "MIT"
