# SPDX-FileCopyrightText: 2020 - 2023 Sami Kouatli <sami.kouatli@allcircuits.com>
# SPDX-FileCopyrightText: 2023 Anthony Loiseau <anthony.loiseau@allcircuits.com>
# SPDX-FileCopyrightText: 2023 Benoit Rolandeau <benoit.rolandeau@allcircuits.com>
#
# SPDX-License-Identifier: LicenseRef-ALLCircuits-ACT-1.1

# Project definition
name: act_permissions_manager
description: Useful classes to manager permissions

# Project configuration
publish_to: none

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  web:
  windows:

environment:
  sdk: ^3.11.1
  flutter: ">=3.29.0"

# Project dependencies
dependencies:
  # Flutter framework
  flutter:
    sdk: flutter

  # Help to implement value based equality without explicit override
  equatable: ^2.0.7

  mutex: ^3.1.0

  # To request permissions (eg. SMS, GPS...)
  # TODO(brolandeau): when updating the lib, verify if we still need to override `permission_handler_android`
  permission_handler: ^12.0.0+1

  # Extend the capabilities of Dart Streams and StreamControllers
  rxdart: ^0.28.0

  # Easily create managers
  act_life_cycle:
    path: ../act_life_cycle

  act_contextual_views_manager:
    path: ../act_contextual_views_manager

  # Extend Dart functionalities
  act_dart_utility:
    path: ../act_dart_utility

  # Default global manager
  act_global_manager:
    path: ../act_global_manager

  # Life cycle manager
  act_app_life_cycle_manager:
    path: ../act_app_life_cycle_manager

  # Logger manager
  act_logger_manager:
    path: ../act_logger_manager

  # Platform manager
  act_platform_manager:
    path: ../act_platform_manager

# Dependencies used by developer
dev_dependencies:
  # API to test Flutter applications
  flutter_test:
    sdk: flutter

  # Recommended lints for Flutter apps
  flutter_lints: ^6.0.0

dependency_overrides:
  # This is needed to fix problem with building for Android app
  # The permission handler doesn't use the latest android package which is needed by flutter.
  permission_handler_android: 13.0.1
