# SPDX-FileCopyrightText: 2026 Benoit Rolandeau <benoit.rolandeau@allcircuits.com>
#
# SPDX-License-Identifier: LicenseRef-ALLCircuits-ACT-1.1

name: act_ffi_utility
description: This package provides utility functions for working with FFI in Flutter.
publish_to: none

# This package supports all platforms listed below.
platforms:
  linux:
  macos:
  windows:

environment:
  sdk: ^3.11.1
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter

  # Equatable for value equality in Dart objects
  equatable: ^2.0.8

  # FFI for native library communication
  ffi: ^2.2.0

  act_config_manager:
    path: ../act_config_manager

  act_dart_result:
    path: ../act_dart_result

  act_dart_value_keeper:
    path: ../act_dart_value_keeper

  # Default global manager
  act_global_manager:
    path: ../act_global_manager

  act_life_cycle:
    path: ../act_life_cycle

  act_logger_manager:
    path: ../act_logger_manager

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
