# SPDX-FileCopyrightText: 2020 - 2023 Sami Kouatli <sami.kouatli@allcircuits.com>
# SPDX-FileCopyrightText: 2023 Anthony Loiseau <anthony.loiseau@allcircuits.com>
# SPDX-FileCopyrightText: 2023 Benoit Rolandeau <benoit.rolandeau@allcircuits.com>
#
# SPDX-License-Identifier: LicenseRef-ALLCircuits-ACT-1.1

# Project definition
name: act_flutter_utility
description: This package contains useful methods and classes which extends
  flutter functionality.

# Project configuration
publish_to: none

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.11.1
  flutter: ">=3.29.0"

# Project dependencies
dependencies:
  # Flutter framework
  flutter:
    sdk: flutter

  # Help to implement value based equality without explicit override
  equatable: ^2.0.7

  # Implement the BLoC (Business Logic Component) design pattern
  flutter_bloc: ^9.1.1

  # SVG image widget
  flutter_svg: ^2.2.0

  # A Flutter plugin for launching a URL.
  # TODO(brolandeau): when updating the lib, verify if we still need to override `url_launcher_android`
  url_launcher: ^6.3.1

  # Tells which amount a widget is currently visible
  visibility_detector: ^0.4.0+2

  act_config_manager:
    path: ../act_config_manager

  act_dart_utility:
    path: ../act_dart_utility

  act_foundation:
    path: ../act_foundation

  # Default global manager
  act_global_manager:
    path: ../act_global_manager

  # Help to know the current internet state on the phone (if we can join internet, or not)
  act_internet_connectivity_manager:
    path: ../act_internet_connectivity_manager

  act_life_cycle:
    path: ../act_life_cycle

# Dependencies used by developer
dev_dependencies:
  # API to test Flutter applications
  flutter_test:
    sdk: flutter

  # Recommended lints for Flutter apps
  flutter_lints: ^6.0.0

dependency_overrides:
  # This is needed to fix problem with building for Android app
  # The url launcher doesn't use the latest android package which is needed by flutter.
  url_launcher_android: 6.3.16
