# SPDX-FileCopyrightText: 2025 Benoit Rolandeau <benoit.rolandeau@allcircuits.com>
#
# SPDX-License-Identifier: LicenseRef-ALLCircuits-ACT-1.1

name: act_websocket_core
description: This package contains the shared WebSocket classes between server and client
publish_to: none

environment:
  sdk: ^3.11.1
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter

  web_socket_channel: ^3.0.3

  act_dart_utility:
    path: ../act_dart_utility

  act_global_manager:
    path: ../act_global_manager

  act_life_cycle:
    path: ../act_life_cycle

  act_logger_manager:
    path: ../act_logger_manager

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
