# SPDX-FileCopyrightText: 2020 - 2023 Sami Kouatli <sami.kouatli@allcircuits.com>
# SPDX-FileCopyrightText: 2023 Anthony Loiseau <anthony.loiseau@allcircuits.com>
# SPDX-FileCopyrightText: 2023 Benoit Rolandeau <benoit.rolandeau@allcircuits.com>
#
# SPDX-License-Identifier: LicenseRef-ALLCircuits-ACT-1.1

# Project definition
name: act_config_manager
description: This package contains methods to manage config variables.
publish_to: none

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.11.1
  flutter: ">=3.29.0"

# Project dependencies
dependencies:
  # Flutter framework
  flutter:
    sdk: flutter

  # Help to implement value based equality without explicit override
  equatable: ^2.0.7

  # Load configuration at runtime from a .env file which can be used throughout the application.
  flutter_dotenv: ^5.2.1

  # Contains utilities for Dart
  act_dart_utility:
    path: ../act_dart_utility

  act_foundation:
    path: ../act_foundation

  # Easily create managers
  act_life_cycle:
    path: ../act_life_cycle

  act_platform_manager:
    path: ../act_platform_manager

  # Contains utilities for Dart
  act_yaml_utility:
    path: ../act_yaml_utility

# Dependencies used by developer
dev_dependencies:
  # API to test Flutter applications
  flutter_test:
    sdk: flutter

  # Recommended lints for Flutter apps
  flutter_lints: ^6.0.0
