# SPDX-FileCopyrightText: 2024 Benoit Rolandeau <benoit.rolandeau@allcircuits.com>
#
# SPDX-License-Identifier: LicenseRef-ALLCircuits-ACT-1.1

name: act_yaml_utility
description: This contains utility classes to manage YAML
publish_to: none

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.11.1
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter

  yaml: ^3.1.3

  # Contains utilities for Dart
  act_dart_utility:
    path: ../act_dart_utility

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
