#!/bin/bash

# SPDX-FileCopyrightText: 2026 Benoit Rolandeau <borlnov.obsessio@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0

set -e

if [ "$1" = "configure" ]; then
    # Update shared library cache
    ldconfig
fi

exit 0
