# SPDX-FileCopyrightText: 2023 Anthony Loiseau <anthony.loiseau@allcircuits.com>
# SPDX-FileCopyrightText: 2023 Benoit Rolandeau <benoit.rolandeau@allcircuits.com>
#
# SPDX-License-Identifier: LicenseRef-ALLCircuits-ACT-1.1

name: act_contextual_views_manager
description: This package is useful to define a skeleton for contextual views
publish_to: none

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.11.1
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter

  # Implement the BLoC (Business Logic Component) design pattern
  flutter_bloc: ^9.1.1

  # Help to implement value based equality without explicit override
  equatable: ^2.0.7

  mutex: ^3.1.0

  act_flutter_utility:
    path: ../act_flutter_utility

  act_global_manager:
    path: ../act_global_manager

  act_life_cycle:
    path: ../act_life_cycle

  act_logger_manager:
    path: ../act_logger_manager

  act_router_manager:
    path: ../act_router_manager

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints for Flutter apps
  flutter_lints: ^6.0.0
