# SPDX-FileCopyrightText: 2023 Benoit Rolandeau <benoit.rolandeau@allcircuits.com>
#
# SPDX-License-Identifier: LicenseRef-ALLCircuits-ACT-1.1

name: act_ocsigen_halo_manager
description: This is the manager for the OCSIGEN implementation of HALO
publish_to: none

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.11.1
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter

  # Help to implement value based equality without explicit override
  equatable: ^2.0.7

  # Easily create managers
  act_life_cycle:
    path: ../act_life_cycle

  # Extend Dart functionalities
  act_dart_utility:
    path: ../act_dart_utility

  # Default global manager
  act_global_manager:
    path: ../act_global_manager

  act_halo_abstract:
    path: ../act_halo_abstract

  act_halo_manager:
    path: ../act_halo_manager

  # Logger manager
  act_logger_manager:
    path: ../act_logger_manager

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints for Flutter apps
  flutter_lints: ^6.0.0
