# SPDX-FileCopyrightText: 2025 Benoit Rolandeau <borlnov.obsessio@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0

# This section contains logger configurations for the application.
logger:
  # Contains configuration elements for the console logger.
  console:
    # Indicates if the console logger is enabled or not.
    enabled: false

    # Indicates the minimum level of logs that will be displayed in the console.
    level: warn
