# SPDX-FileCopyrightText: 2026 Benoit Rolandeau <borlnov.obsessio@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0

name: Markdown Lint

on:
  push:
    branches: [main]
    paths:
      - "**/*.md"
      - ".markdownlint.yaml"
      - ".github/workflows/markdown_lint.yml"
  pull_request:
    paths:
      - "**/*.md"
      - ".markdownlint.yaml"
      - ".github/workflows/markdown_lint.yml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
    - uses: DavidAnson/markdownlint-cli2-action@ded1f9488f68a970bc66ea5619e13e9b52e601cd # v23.2.0
      with:
        globs: |
          **/*.md
          !actlibs/**
          !build/**
          !.dart_tool/**
          !test/*.md
          !**/.git
          !**/node_modules
